steps:
- pwsh: |
    git merge origin/master -s recursive -X theirs
    $savedMSBuildExtensionsPath = $env:MSBuildExtensionsPath
    $env:MSBuildExtensionsPath = 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild'
    dotnet new sln --name=Uno.Samples.generated
    dotnet sln Uno.Samples.generated.sln add (Get-ChildItem -Recurse *.csproj)
    $env:MSBuildExtensionsPath = $savedMSBuildExtensionsPath

- task: UseDotNet@2
  inputs:
    packageType: 'runtime'
    version: '2.2.0'

- task: nventiveCanaryUpdater@5
  inputs:
    solution: Uno.Samples.generated.sln
    usePrivateFeed: false
    useNuGetOrg: true
    mergeBranch: false
    nugetUpdaterVersion: '2.1.1'
    allowDowngrade: true
    packageAuthor: 'nventive'
    summaryFile: '$(Build.ArtifactStagingDirectory)/Summary.md'
    resultFile: '$(Build.ArtifactStagingDirectory)/Results.json'

- powershell: |
    dotnet tool uninstall nventive.nuget.updater.tool --tool-path $(Agent.TempDirectory)

- task: nventiveCanaryUpdater@5
  inputs:
    solution: Uno.Samples.generated.sln
    usePrivateFeed: false
    useNuGetOrg: true
    mergeBranch: false
    nugetUpdaterVersion: '2.1.1'
    allowDowngrade: true
    packageAuthor: 'Uno Platform'
    summaryFile: '$(Build.ArtifactStagingDirectory)/Summary-Uno.md'
    resultFile: '$(Build.ArtifactStagingDirectory)/Results-Uno.json'
